_target_: src.models.brats_module.BraTSLightningModule
lr: 0.0001
net:
  _target_: monai.networks.nets.UNet
  spatial_dims: 3
  in_channels: 4
  out_channels: 4
  channels: [16, 32, 64, 128, 256]
  strides: [2, 2, 2, 2]
